#!/bin/bash
# Chatgen server start
rseed=3629077
counter=1
while [ $counter -le 100 ]
do 
python3 t14gen.py --model_type=gpt2 --model_name_or_path=gpt2-xl --top_k=40 --top_p=1 --length=60 --repetition_penalty=1 \
--char1=Sarah --char2=Mark --char3=Norman --char4=Vanessa \
--context="In closing, where do we go from here?  What does the future hold?  Will this pandemic end?  Will things be back to normal?  What are you going to do now?" \
--seed=$rseed
echo $counter
scp -i ~/chatgen.pem Scene* ubuntu@ec2-18-219-113-41.us-east-2.compute.amazonaws.com:/home/ubuntu/jul25/
((counter++))
((rseed++))
done
echo All done

